= Course Reserves
Kevin Beswick
Victoria Lacroix

A little system to allow for reserves on courses. Professors can ask that required material for a course be reserved, allowing students easier access to said material.

== Requirements

* +Python 3+
* +Python-LDAP+
* +Flask+
** +Flask-Login+
** +Flask-Babel+
** +Flask-BabelEx+
* +PostgreSQL+
** +PsycoPG2+
* +Twisted+

You can install the prerequisites using +pipenv+:

    pipenv install

== Installation

As long as the requirements are met, this *should* work with very little effort. You'll need your usual WSGI stuff to get it working on a web server. This application was developed on an nginx server, so that's where one will get the best results.

+schema.sql+ has all of the SQL code to generate the tables that are needed. +config.ini+ stores the username and database used, so one need simply change those to whatever is desired.

Speaking of +config.ini+, a secret key must be set in there. This is a key used to sign session variables/cookies. Try not to make it public.
