= Course Reserves
Kevin Beswick
Victoria Lacroix

A little system to allow for reserves on courses. Professors can ask that required material for a course be reserved, allowing students easier access to said material.

== Requirements

* +Python 3+
* +Python-LDAP+
* +Flask+
** +Flask-Login+
** +Flask-Babel+
** +Flask-BabelEx+
* +PostgreSQL+
** +PsycoPG2+
* +Twisted+

You can install the prerequisites using +pipenv+:

    pipenv install

== Installation

As long as the requirements are met, this *should* work with very little effort.

+schema.sql+ has all of the SQL code to generate the tables that are needed. +config.ini+ stores the username and database used.

Speaking of +config.ini+, a secret key must be set in there. This is a key used to sign session variables/cookies. Try not to make it public.

== Configuration

An example nginx server block, if you set the port to 8888, might look like the following:

    rewrite ^/reserves/?$ /reserves/en/ redirect;

    location /reserves/ {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_headers_hash_max_size 2048;

        proxy_pass http://127.0.0.1:8888/;
        proxy_redirect     ~http://127.0.0.1:8888/(.*)$ http://127.0.0.1/reserves/$1;
    }

Note that on SELinux-enabled systems like Fedora, you will likely need to allow web servers to connect to HTTP:

    setsebool -P httpd_can_network_connect 1
